stages:          
  - build
  - test
  - deploy

build-job:       
  stage: build
  script:
    - echo "上传文章"
    - cd /opt/blog
    - sh gitpull.sh
    - echo "上传完成."
  tags:
    - dev

unit-test-job:   
  stage: test
  when: manual
  script:
    - echo "重启hugo."
    - sleep 60
    - echo "Code coverage is 90%"
  tags:
    - dev

deploy-job:      
  stage: deploy
  when: manual
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  tags:
    - dev
