stages:          
  - build
  - docker
  - deploy

build-job:       
  stage: build
  script:
    - echo "上传文章"
    - cd /opt/blog && sh gitpull.sh
    - echo "上传完成."
  tags:
    - dev

build-docker-job:   
  stage: docker
  when: manual
  script:
    - echo "生成 docker hugo."
    - cd /opt/blog && sh updatedocker.sh
    - echo "结束 end"
  environment:
    name: production
    url: https://www.nbtyfood.com
  tags:
    - dev

deploy-job:      
  stage: deploy
  when: manual
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  tags:
    - dev
